name: C++ with CMake CI

on: [push, pull_request]

jobs:
  SHM:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@SHM
    - name: mkdir shm/build
      run: mkdir shm/build
    - name: Compile
      working-directory: shm/build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: shm/build
      run: ctest -V
